name: Hola mundo

on:
  push:
    branches: [aprendiendo-github-actions]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run hola-mundo.js
        run: node hola-mundo.js
